apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-test-{{ .Values.pvc.storageClass }}
spec:
  storageClassName: {{ .Values.pvc.storageClass | required ".Values.pvc.storageClass is required!" }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}